version: '3.7'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./scripts/sql-script:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - melinet

  challenge-meli:
    container_name: rest-server
    build:
      context: .
      target: deployer
    env_file:
      - .env
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    volumes:
      - .:/app
    networks:
      - melinet
volumes:
  mysql-data:
networks:
  melinet:
